# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ayush Singh's Thoughts and Writings
description: >- # this means to ignore newlines until "baseurl:"
    Thoughts on math, music, books, and nature.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

email: ayush.singh@niser.ac.in
obf_email: ayush [dot] singh [at] niser [dot] ac [dot] in
github_username:  11DE784A

# License information
license:
  name: CC BY-NC-SA 4.0
  link: https://creativecommons.org/licenses/by-nc-sa/4.0/


# Books I am currently reading
currentbooks:
  - title: Free Culture
    author: Lawrence Lessig

  - title: Brave New World
    author: Aldous Huxley

        
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives

# Syntax highlighting
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
